steps:
  # Step 1: Building the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/weather-data-api', '.']

  # Step 2: Uploading the image to Artifact/Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/weather-data-api']

  # Step 3: Automatic deployment in Google Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'weather-data-api'
      - '--image'
      - 'gcr.io/$PROJECT_ID/weather-data-api'
      - '--region'
      - 'us-central1'

# Force writing logs directly to the Google Cloud console
options:
  logging: CLOUD_LOGGING_ONLY